# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 22:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_auto_20180219_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('venue', models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='venue should contain only alphabets and numbers', regex='^[0-9a-zA-Z\\s]*$')])),
                ('city', models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.RegexValidator(code='invalid_city', message='city should contain only alphabets', regex='^[a-zA-Z\\s]*$')])),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('status', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('INPROGRESS', 'Inprogress'), ('COMPLETED', 'Completed')], default='ENQUIRY', max_length=15)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
