# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booked_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_service',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_served', to='customers.Vendor'),
        ),
    ]
