# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_staff'),
        ('booking', '0003_auto_20180223_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_service',
            name='staff',
            field=models.ManyToManyField(related_name='staff_assigned', to='customers.Staff'),
        ),
    ]
