# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booked_service_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_service',
            name='staff',
            field=models.ManyToManyField(related_name='services_assigned', to='customers.Staff'),
        ),
    ]
