# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 06:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180224_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='advance',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(10, message='Advance should be greater than 10'), django.core.validators.MaxValueValidator(10000000, message='Advance should be less than 10000000')]),
        ),
    ]
