# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_event_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='advance',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Advance should be greater than 0'), django.core.validators.MaxValueValidator(10000000, message='Advance should be less than 10000000')]),
        ),
    ]
