# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
