# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_staff'),
        ('booking', '0006_event_advance'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payins', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='payin',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_payins', to='booking.Event'),
        ),
    ]
