# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180224_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payins',
        ),
        migrations.AddField(
            model_name='payin',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payins', to='accounting.Invoice'),
        ),
    ]
