# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-24 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180324_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 14, 29, 1, 142815, tzinfo=utc), verbose_name='date commission is paid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='due_date',
            field=models.DateField(verbose_name='date commission is expected'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='generated_date',
            field=models.DateField(verbose_name='date commission generated'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='payouts',
            field=models.ManyToManyField(related_name='Payouts', to='accounting.PayCommissionOrSalary'),
        ),
    ]
