# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20180224_1837'),
        ('accounting', '0006_auto_20180324_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='payouts',
        ),
        migrations.RemoveField(
            model_name='payin',
            name='invoice',
        ),
        migrations.AddField(
            model_name='commission',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_commissions', to='booking.Event'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PARTIAL_PAYMENT', 'Partially Paid'), ('PAID', 'paid fully'), ('CLOSED', 'Closed')], default='CREATED', max_length=15),
        ),
    ]
