# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20180324_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='date payout is made'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='date payment is expected'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(verbose_name='date payout is expected'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='generated_date',
            field=models.DateField(verbose_name='date bill generated'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PARTIAL_PAYMENT', 'Partially Paid'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='CREATED', max_length=15),
        ),
    ]
