# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 00:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180330_0351'),
        ('customers', '0009_staff'),
        ('accounting', '0008_auto_20180330_0351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commission_Structure',
            new_name='CommissionStructure',
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0, message='Amount should be greater than 0'), django.core.validators.MaxValueValidator(10000000, message='Amount should be less than 10000000')]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='billed_Payouts', to='accounting.Payout'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionstructure',
            unique_together=set([('staff', 'service')]),
        ),
    ]
