# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_staff'),
        ('accounting', '0009_auto_20180330_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_payouts', to='customers.Vendor'),
            preserve_default=False,
        ),
    ]
