# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-31 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_payout_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='payouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='commissions', to='accounting.PayCommissionOrSalary'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payins',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoices', to='accounting.Payin'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='bills', to='accounting.Payout'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='paid',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0, message='Amount should be greater than 0'), django.core.validators.MaxValueValidator(10000000, message='Amount should be less than 10000000')]),
        ),
    ]
