# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-18 19:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170610_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Quantity should be greater than 0'), django.core.validators.MaxValueValidator(100000, message='Quantity should be less than 100000')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_name', message='name should contain only alphabets', regex='^[0-9a-zA-Z\\s]*$')]),
        ),
    ]
