# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-29 22:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180219_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(code='invalid_name', message='name should contain only alphabets', regex='^[0-9a-zA-Z\\s]*$')]),
        ),
    ]
